TesteApplication/TesteApplication/Models/AtividadeModels.cs
namespace TesteApplication.Models
{
    public class AtividadeListModel
    {
        public Int64? Id { get; set; }
        public String? DataHoraInicial { get; set; }
        public String? DataHoraFinal { get; set; }
        public Double Minutos_Diferenca { get; set; }
        public Int64 Ano_Referencia { get; set; }
        public Int64 Distancia { get; set; }

    }

    public class AtividadeCadastroModel
    {
        public virtual String? DataInicialString { get; set; }
        public virtual String? DataFinalString { get; set; }
        public virtual Int64? DistanciaMetros { get; set; }
    }
}

TesteApplication/TesteApplication/Models/ErrorViewModel.cs
namespace TesteApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TesteApplication/TesteApplication/Controllers/AtividadeController.cs
using Microsoft.AspNetCore.Mvc;
using TesteApplication.ControllersWebApi;
using TesteApplication.Models;

namespace TesteApplication.Controllers
{
    public class AtividadeController:Controller
    {
        public IActionResult Index() 
        {
            return View();
        }

        public IActionResult Cadastro(Int64? Id) 
        {
            return View();
        }
        [HttpPost()]
        public async Task<ActionResult> Cadastro(AtividadeCadastroModel model )
        {
            using (var api = new AtividadeApiController()) 
            {
                 await api.Save(model);
            }
            return View(model);
        }



    }
}

TesteApplication/TesteApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TesteApplication.Models;

namespace TesteApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TesteApplication/TesteApplication/Views/Atividade/Cadastro.cshtml
@model AtividadeListModel
@using TesteApplication.Models
@{
    Layout = "_Layout";
}
@section Scripts
    {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tensorflow/3.20.0/tf.min.js"></script>
    <script>

        //Inserção de Atividade
        async function enviar() {
            let ok = false;
            let url = "https://localhost:44388/AtividadeApi/SetAtividadeManually";
            const campoInicial = `${document.querySelector("#id_CampoDataInicial").value} ${document.querySelector("#id_CampoHorarioInicial").value}`,
                campoFinal = `${document.querySelector("#id_CampoDataFinal").value} ${document.querySelector("#id_CampoHorarioFinal").value}`,
                campoDistancia = `${document.querySelector("#id_DistanciaMetros").value}`;


            let options = {
                "method": "POST",
                "headers": { "Content-Type": "application/json" },
                "body": JSON.stringify({
                    dataInicialString: campoInicial,
                    dataFinalString: campoFinal,
                    DistanciaMetros: campoDistancia,

                }),
                //mode:"no-cors"
            }
            try {
                let apireq = await fetch(url, options).then(function(data) { console.log(data); });
                ok = true;
            }
            catch (ex) {
                ok = false;
            }
            return ok;
        }
        let sendButton = document.querySelector("#idEnviar");
        sendButton.addEventListener("click", async function() {
            let mensagem = await enviar();
            if (!mensagem) {
                console.log("Erro!");
            }
        })



    </script>
}
    <div>
        <!--Criação da Linha-->
        <h5> Inserção de Nova Atividade </h5>
        <div class="row justify-content-center">

            <!--Criação da Coluna ( Data Inicial )-->
            <div class="col-sm-3">

                <label for="id_CampoDataInicial"> Data Inicial: </label>
                <input type="date" id="id_CampoDataInicial" class="form-control" />

            </div>

            <!--Criação da Coluna ( Data Final )-->
            <div class="col-sm-3">

                <label for="id_CampoDataFinal"> Data Final: </label>
                <input type="date" id="id_CampoDataFinal" class="form-control" />

            </div>
        </div>

        <div class="row justify-content-center mt-2">

            <div class="col-sm-3">
                <label for="id_CampoHorarioInicial"> Horário Inicial: </label>
                <input type="time" id="id_CampoHorarioInicial" class="form-control" />

            </div>
            <div class="col-sm-3">
                <label for="id_CampoHorarioFinal"> Horário Final: </label>
                <input type="time" id="id_CampoHorarioFinal" class="form-control" />

            </div>

        </div>
        <div class="row justify-content-center mt-2">
            <div class="col-sm-2">
                <label for="id_DistanciaMetros">Distancia (em Metros):</label>
                <input id="id_DistanciaMetros" type="number" min="1" class="form-control" />
            </div>
        </div>
        <div class="row mt-4">

            <div class="text-center">
                <input type="button" class="btn btn-success" id="idEnviar" value="Enviar" />
            </div>

        </div>

    </div>

TesteApplication/TesteApplication/Views/Atividade/Index.cshtml
@model AtividadeListModel
@using TesteApplication.Models
@{
    Layout = "_Layout";
    //ViewBag.Titulo = "Listagem de Atividades";
    ViewData["Title"] = "Listagem de Atividades";
}
@section Scripts
    {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tensorflow/3.20.0/tf.min.js"></script>
    <script>

        class Atividades {
            constructor(objeto) {
                this.text = JSON.stringify(objeto);
                this.data = JSON.parse(this.text);
            }
        }

        //Função machine learning
        async function AprendizadoLinear(atv, epochs = 0) {
            //Quantidade de iterações de treinamento
            const model = tf.sequential({
                layers: [tf.layers.dense({ units: 1, inputShape: [1] })]
            });
            model.compile({ optimizer: 'sgd', loss: 'meanSquaredError' });

            let arrayDistancia = [],
                arrayMinutos = [];
            atv.forEach(item => arrayMinutos.push(item.minutos_Diferenca));

            const tensorx = tf.tensor2d(arrayDistancia, [(arrayDistancia.length - 1), 1]);
            const tensory = tf.tensor2d(arrayMinutos, [(arrayMinutos.length - 1), 1]);
            //momento do aprendizado
            let testeTempo = false;
            let testeDistancia = false;

            let treinamento = null;
            if (testeTempo) {
                treinamento = await model.fit(tensorx, tensory, {
                    //batchSize: 4,
                    epochs: epochs
                });
            }

            let previsao = model.predict([array[array.length - 1]], [1, 1]);
            document.querySelector("#idResponseML").innerHTML = previsao.toString();

            return model;
        }

        async function captureRecordsAtividade() {
            let obj = null;
            let url = "https://localhost:44388/AtividadeApi/GetRecords",
                options = {
                    method: "GET",
                    headers: {
                        "Content-Type": "application/json",
                    }
                }

            await fetch(`${url}`, options).then(data =>
                data.json())
                .then(results => {
                    obj = new Atividades(results);
                });
            return obj;
        }

        function generateHtmlText(atividades) {

            let element = document.querySelector("#idRowAtividade");
            element.classList.add("overflow-scroll");

            let text = `<ul class = "list-unstyled">`;

            for (var item of atividades.data) {

                Object.keys(item).forEach((parameter, index) => {

                    text += `<li class="fs-14">${parameter} - ${item[parameter]}</li>`;

                });
            }
            text = text + "</ul>";
            element.innerHTML = text;

        }

        let atv = null;
        const getAtividade = Promise.resolve(captureRecordsAtividade()).then(data => atv = data);



        let ML = document.querySelector("#id_ML");
        ML.addEventListener("click", async function() {
            try {
                if (document.querySelector("#idRowAtividade").innerHTML == ``) {
                    throw "Base não Listada";
                }
                else {
                    await AprendizadoLinear(atv.data, 20);
                }
            }
            catch (ex) {
                console.log(ex);
            }
        });
        document.addEventListener("DOMContentLoaded", function() {
            document.querySelector("#idRowAtividade").innerHTML = "";
        });
    </script>
}
    <div>
        <h5><span>@ViewData["Title"] </span> </h5>
        <!--Criação da Linha-->
        <div class="card">

            <div class="card-body text-center">
                <a class="text-decoration-none" href="javascript:void(0)" id="idGenerateBase" onclick="generateHtmlText(atv)">Visualizar Base de Treino</a>

            </div>

            <div class="row text-center" style="max-height:100px;" id="idRowAtividade">
            </div>



        </div>
        <div class="container-fluid">
            <a class="text-decoration-none" href="javascript:void(0)" id="id_ML">Realizar esquemas de Machine Learning</a>
            <div class="row text-center" id="idResponseML">
            </div>

            <a href="@Url.Action("Cadastro","Atividade")" class="btn btn-info text-white">Gerar nova Atividade</a>
        </div>

    </div>

TesteApplication/TesteApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Exemplo de uso do <a href="@Url.Action("Index","Atividade")">TensorFlow:</a></p>
</div>

TesteApplication/TesteApplication/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "DevKNOW Application";
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Development</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TesteApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TesteApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - @ViewData["Title"] - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>